### ISSUE TITLE
Setup Environment

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#1]
### Backend
- [x] Node
- [x] Hapi

### React
- [x] React
- [x] Router
- [x] Redux
- [x] Redux-Thunk

### Linting
- [x] ESLint

### Testing 
- [x] Tape
- [x] Istanbul
- [x] JSDom
- [x] Circle CI 
- [x] GitHooks
- [x] React-Test-Utils 

~~Maybe Enzyme by AirBnB~~ No need

### Database
- [x] Redis

### Design 
- [x] SASS

**Comment by sohilpandya** [comment]
https://css-tricks.com/snippets/css/a-guide-to-flexbox/ - Look into Flexbox

**Comment by sohilpandya** [comment]
### Linter
http://eslint.org/docs/rules/

**Comment by minaorangina** [comment]
All done!
