### ISSUE TITLE
Feed Screen, Differentiation between Poll and Event

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#104]
HI @rickardinho & @Dameodeare,

We have been discussing the layout for Feed page, and this is how we feel it should be displayed: 

* If it is a poll, then show TBC for date, time and place, even if any of the options are confirmed ( as shown in 5-Back feed page.pdf, item 3 & 4 in the list. )
* If it's an event, then show all the relevant date, time and place for the event. 

This will allow users to easily differentiate between and event and a poll with a single glance at the feed page, having partial information in the poll would probably cause confusion in the mind of a user. 

Let us know your thoughts.

**Comment by rickardinho** [comment]
Hi @sohilpandya & @minaorangina,
cc: @Dameodeare, 

If one of the date & time or place has been decided (i.e. only one option in the poll), then I think this should be displayed (its useful information and also future-proofs the app for calendar sharing where the user might want tentative invites/polls synced to their calendar).

It's a good point you've raised though about being able to easily differentiate between an invite and a poll in the feed.  Could we use small icons (similar to item 1 in 5-Back feed page.pdf) to highlight the action of each item... we think its probably best to place this just to the left of the "Just now" text.  We will have to get our designer to come up some icons, so perhaps you could use placeholders for now or if you have some stock icons, go with these for now and we can refresh later.

Does this work for you? 
Dave

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare  Feed notification currently displays confirmed event details and shows TBC.  Lacking icons for now so I'll keep this issue open until this is completed.

This is linked to #166: I've realised the *TBC on the feed would be ambiguous.  There's a difference between TBC as in *the host will decide later*, and TBC as in *this is an option to vote on*.

**Comment by rickardinho** [comment]
Hi @minaorangina 
We think it would probably be best if we could differentiate.  Perhaps 'the host will decide later' should say "TBC" and 'this is an option to vote on' should say something like "Vote" or an equivalent icon (if intuitive).
