### ISSUE TITLE
Date and Time - can Time be left blank

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#109]
Hi @minaorangina and @sohilpandya ,
cc: @Dameodeare ,
In testing the create event flow, I had question relating to the date and time.
Can time be left blank? (i.e. only choose dates to poll on).  It can be a bit tedious to enter times at the polling stage, particularly if polling on 3 dates (for example a house party or drinks where its likely to always be the evening).  Time needs to be there when confirming but I wondered if it could default to "All day" as with google calendar until a time is chosen.

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare  So to clarify: when creating an event, a user is able to click `Next` if they have not supplied a time.  But the time input will still be there, should they choose to use it?

**Comment by rickardinho** [comment]
Hi @minaorangina and @sohilpandya,
We've had a chat and we think this is how we would like it to look:
1. once they have selected a date, the time defaults to "TBC" in the create event screen.
2. user is able to click Next once a date has been chosen, but if they want they can leave the time as "TBC".
3. If time is "TBC" then time is hidden from the poll screen or the confirmed event screen.
4. If they go back to edit the event then they can still choose a time or leave it as "TBC".

Does this make sense?
Dave

**Comment by minaorangina** [comment]
@rickardinho Yep, makes sense.  Essentially, the user is never obliged to set a time for an event (or poll), but can go back and add one whenever.  We'll make those changes in due course.

**Comment by rickardinho** [comment]
Yes. That's right.
