### ISSUE TITLE
Removing inputs

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#110]
Hi @minaorangina and @sohilpandya ,
When removing an input from the create event screens, it automatically deletes the last item in the list.  Can we have "X" next to each item to remove them as the user might want to remove the first or middle item in a list rather than the last one?

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare Thanks for opening the issue, we'll look at this

**Comment by minaorangina** [comment]
Currently eventWhere input behaves strangely after changing `defaultValue` attribute to `value`
