### ISSUE TITLE
Setup db for voting

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#118]
Relates to #100 

- [x] When user votes, userid is added to the relevant set (created on the fly)

**Comment by minaorangina** [comment]
#### Voting structure
* Up to 9 sets to represent the `what`, `where` and `when` options
* A vote is represented by a user's presence in the relevant set
* Total count == sum of lengths of sets

**Comment by sohilpandya** [comment]
structure for sets is `vote:eventID|eventType:[index]`
