### ISSUE TITLE
Latest wireframes

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#15]
Hey @rickardinho @Dameodeare,

Hope you are doing well, we've had a good day setting up our development environment today.

We just wanted to get all the wireframes for our planning sessions, if you could email us a copy of all the wireframes (old & new) that would be great! 

Thanks

**Comment by rickardinho** [comment]
Hi Sohil,
These are the full wireframe we have. I think we sent these before but let
me know if you think there's anything else you don't have.  These were all
created before our meetings and some screens may have changed slightly due
to outt agreed scope.
Dave

**Comment by sohilpandya** [comment]
Hi @rickardinho, there was no attachment in the email.

**Comment by sohilpandya** [comment]
@rickardinho We already have the black and white ones, but we'd like the colour wireframes that you had bought in for our first few meetings. 😄

**Comment by rickardinho** [comment]
Hi Sohil, I attached a PDF. It's showing as attached in my sent items. I'm
trying again.
Dave

**Comment by rickardinho** [comment]
Sorry, the colour files are quite large so I've included links below to our
Google Drive which you should be able to download them from.  Let me know
if it doesn't work. Dave

https://drive.google.com/folderview?id=0B8TOihZPZ2bMbWpUWXNVa0V0WDQ

https://drive.google.com/folderview?id=0B1SDAugx7zVxNUpLRzF1SEIyczg

**Comment by sohilpandya** [comment]
Thanks @rickardinho

**Comment by minaorangina** [comment]
Hi @rickardinho @Dameodeare some of the files in this link https://drive.google.com/folderview?id=0B1SDAugx7zVxNUpLRzF1SEIyczg are not visible and show up with an error. 

Any chance you can send them to us again please, preferably in PNG format.
