### ISSUE TITLE
Chores: Monday 16th May

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#155]
- [x] Fix text spacing in event where
- [x] Clear poll redux state
- [x] Fix rest of create event css
- [x] CSS for poll
- [x] event name and description throughout create-event
- [x] remove create new event button from feed, clear the navbar
- [x] loading css issue #150

**Comment by sohilpandya** [comment]
@minaorangina do we need the discard event button on the confirm page of event creation? or can we just have the cancel button at the top which works fine.

**Comment by minaorangina** [comment]
@sohilpandya very true, I guess we don't need it.

**Comment by sohilpandya** [comment]
@minaorangina ok, I'll remove that button. 👍
