### ISSUE TITLE
Nest buttons in Link tag

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#164]
Buttons should be nested inside the `Link` tags to make entire button element clickable.

@rickardinho

**Comment by sohilpandya** [comment]
@rickardinho we have fixed this, can you please confirm that it works ok when you click around the whole button.

**Comment by rickardinho** [comment]
Hi @sohilpandya and @Dameodeare , I can confirm this looks to be fixed now.  Cheers.
Dave
