### ISSUE TITLE
Host can create a confirmed event and leave details as TBC

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#166]
@rickardinho @Dameodeare , currently if the user leaves a text field blank, the app assumes the user meant to remove it and cleans things up.

If the TBC functionality hinged on a text field being left blank, the app can't know if a blank field was a conscious choice by the user or a spare field that the user forgot to remove.  

The clean up functionality can be removed, which would solve this. But I would suggest perhaps having a dedicated TBC button?  That way, the difference between a conscious choice to leave mark something TBC would be clear, and we can leave the cleaning up of spare text fields as it is.

This would have to be weighed up with making sure the page didn't look too cluttered.  Tell me what you think.

**Comment by rickardinho** [comment]
@minaorangina, are you saying that the user can progress by clicking Next even if a field is left blank?  Currently on my version I don't see the next button unless there is something entered in at least one of the fields.

**Comment by minaorangina** [comment]
@rickardinho no, so the user can't progress if the first field is empty. But they can if they add extra fields and leave those blank, as long as there's something in the first one.  The app currently makes sure you don't end up creating a poll with empty values, which is what would happen. 

We can easily make it so the button is always visible if you like, and assume if a user has left a field blank that they mean to confirm later. In which case there should probably be a little message letting the user know they can do that. I doubt a user would realise that was an option otherwise.

**Comment by rickardinho** [comment]
@Dameodeare so I think our two options are: 1. have a tbc button as Mina suggested or 2. allow them to leave blank (which defaults to TBC) with a piece of text informing them of this.  What are your thoughts?

**Comment by Dameodeare** [comment]
i prefer option 2.

**Comment by rickardinho** [comment]
Hi @minaorangina,
We think option 2 above is better.  So when the user leaves the first option blank and click Next it is registered as a TBC.  Then as your suggestion, add some text that says something like "or leave blank to decide later".  This keeps the screen less cluttered with buttons and keeps it slick/fast to create an event.

**Comment by minaorangina** [comment]
@Dameodeare @rickardinho Ok great, we will make those changes

**Comment by minaorangina** [comment]
- [ ] Next button always visible
- [ ] Disable empty fields clean-up
- [ ] empty values handled properly in redis
- [ ] Notifications / calendar displays Vote or TBC where necessary
- [ ] Instructions for user

**Comment by sohilpandya** [comment]
@rickardinho @Dameodeare Please have a look at the flow, and close the issue if everything is as expected.

**Comment by rickardinho** [comment]
Hi @sohilpandya this looks to be working as I'd expect.  Feed shows everything correctly too.
Good work.
Dave
