### ISSUE TITLE
getPoll and getVotes function need to be rewritten

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#175]
Hi @rickardinho & @Dameodeare 

Just letting you know of a bug that exists in the current app in the `invitee poll section` and `host tally section`.

At times, it does not remember all the selected votes, hence it may go back to blank even if it has been selected previously. 

Just letting you know of it, so that you are aware of it during testing.

Regards

**Comment by minaorangina** [comment]
@sohilpandya Ended up mimicking the patterns suggested on [this blogpost](http://mostafa-samir.github.io/async-iterative-patterns-pt1/) to deal with iterating asynchronously

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare we've now fixed this: when voting and viewing all votes, everything should behave normally
