### ISSUE TITLE
User access for testing

### ISSUE THREAD

**Issue by Dameodeare** [DRDD2016/app#176]
Can we add a.j.needham@gmail.com & loes.jeurissen@gmail.com to the approved list so we can do some testing please?  They should both have registered on our website a few weeks ago.

Thanks - Damian

**Comment by minaorangina** [comment]
@Dameodeare No problem, do you have their facebook usernames or facebook ids?  I'll need those in order to add them

**Comment by Dameodeare** [comment]
a.j.needham
loes.jeurissen/

**Comment by minaorangina** [comment]
@Dameodeare all done!
