### ISSUE TITLE
Scroll issue on input screens

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#188]
When creating an event , on the what and where screens the second text input box is hidden when typing (the screen is not scrolling to account for the keyboard popping up). However, it seems to work fine on the first and third inputs, where the screen scrolls to account for the keyboard. I'll email a screenshot which shows this.

**Comment by rickardinho** [comment]
screenshot below shows the second input box being hidden by the keyboard when typing in it.
![shot_2016-05-20_09-01-45](https://cloud.githubusercontent.com/assets/17908724/15448695/cc349886-1f60-11e6-8f18-e25f9b2d70e2.png)

**Comment by rickardinho** [comment]
but this screenshot shows the 3rd input box correctly displayed whilst typing in it.
![shot_2016-05-20_09-03-39](https://cloud.githubusercontent.com/assets/17908724/15448697/ec00ced2-1f60-11e6-81e9-4c4df1f4163b.png)

**Comment by sohilpandya** [comment]
Hi @rickardinho,

Thanks for creating this issue, we've had a look at this on an android phone and were having the same issue as you.

After doing some research, we've found that the android soft keyboard pushes the content of the webpage up as standard, but we think there is a way around it, we will get back to you once we have implement it.

**Comment by minaorangina** [comment]
@rickardinho This should now be resolved.  Please give me your feedback - close this issue if you're satisfied.

**Comment by rickardinho** [comment]
Yes, it looks like this has now been fixed.. much better :)
