### ISSUE TITLE
Submit button causing undefined 

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#189]
When entering text inputs for where, using submit button (right arrow) using android keyboard, "undefined" is appended to the text input.

**Comment by rickardinho** [comment]
Screenshot shows the output
![shot_2016-05-20_09-03-39](https://cloud.githubusercontent.com/assets/17908724/15448686/84f9e02a-1f60-11e6-9c72-bd4a428ec6bf.png)

**Comment by minaorangina** [comment]
on enter, for some reason the SET_EVENT_WHERE action is being dispatched.  placeAddress is not defined at that point.

Also, we are binding the handleEventWhere function (in event-where.jsx) in a strange way.  Changing it breaks the input field below.  Worth trying to understand what's happening there.

**Comment by minaorangina** [comment]
Solved the issue like this:
![screen shot 2016-05-31 at 18 42 18](https://cloud.githubusercontent.com/assets/8915092/15684549/76e3b50e-275f-11e6-81d5-291a36156c35.png)

**Comment by sohilpandya** [comment]
Can you please check this, it should no longer come up as undefined. @rickardinho @Dameodeare

**Comment by rickardinho** [comment]
Hi @sohilpandya,
Yes this seems to be fixed.  I'm closing the issue.
Dave
