### ISSUE TITLE
Cast Vote button hidden on iphone 

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#190]
On iphone 5s the cast vote and save event button is hidden as screen doesnt scroll correctly when inputs are added.

**Comment by rickardinho** [comment]
Hi @minaorangina and @sohilpandya 
Just to let you know that we still have this issue which means we can't really test any of the poll functionality on the iphone as we can't respond to polls.  Just so you are aware.
Dave

**Comment by sohilpandya** [comment]
http://stackoverflow.com/questions/22159736/margin-bottom-doesnt-want-to-work-in-opera-and-safari

Issue specific to safari and opera, we can't set a height for the body as that causes issues. so removed it.

**Comment by rickardinho** [comment]
Yes, this is now fixed. Thanks
