### ISSUE TITLE
Screen display in iphone 5s - portrait mode

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#191]
On Iphone 5s - in portrait mode the screen isn’t rendering properly - see screenshots (okay in landscape)
![image1](https://cloud.githubusercontent.com/assets/17908724/15448508/69042e70-1f5b-11e6-91ed-2bf52a71a66c.PNG)

**Comment by sohilpandya** [comment]
@rickardinho this has been fixed, we will be updating live site soon, please confirm here once you have seen the fix.

Thanks

**Comment by rickardinho** [comment]
Hi @sohilpandya 
This looks to be fixed now. just tried this on an iphone 5s and it looks as expected.
Dave
