### ISSUE TITLE
iphone 4 support

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#192]
Iphone 4 - nothing displayed in safari web browser once I have logged in to Facebook.  If I refresh the page it still shows an empty white page.  Is iphone 4 supported or is it too old?

**Comment by sohilpandya** [comment]
@rickardinho we suspect it might be too old, but we've asked a colleague to bring their old iPhone in so that we can test. 

get back to you with the result.

**Comment by rickardinho** [comment]
Doesn't work on iphone 4, but closing this issue as its not a priority.  Just so you are aware.
