### ISSUE TITLE
As a user I want to be able to edit event options during polling

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#193]
As a user I want to be able to edit event options during polling.  I.e. if i want to change the options for what, where or when I can do so.  Votes will then be set to zero if people have already voted for the previous (now deleted) option.

**Comment by minaorangina** [comment]
@sohilpandya and I have had a look at this.  This feature would be quite tricky to implement, and to do it properly would take a fair amount of time.  For instance, controlling for if a hosts deletes an option whilst an invitee is voting for it simultaneously.  Also, we would have to unpick a lot of the current code structure.

It would need around 3 days, which would be probably better spent elsewhere at this stage - a lot of time is needed to make the photo sharing feature work well.  What are your thoughts?

**Comment by rickardinho** [comment]
Hi @minaorangina and @sohilpandya,
Maybe a simpler solution would be to copy the current event poll options to a new event, and then cancel the old event.  The user can then edit the new event without the problems of having to amend polls whilst they are being voted on by other users.

How did you imagine the Cancel button working in the instance that another user is voting at the same time?

@Dameodeare  and I can be available for a call tomorrow if you want to discuss.

Dave

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare So cancelling an event is straightforward.  If a user tries to vote on a non-existent thing, it's fairly trivial to handle for that.  It's less trivial if a user tries to vote on something that's morphed from one thing to another, and it's something we'd have to consider.

We can have a chat on the phone if you like.  Tell us what time suits and we'll email a number for you to contact us on.

**Comment by rickardinho** [comment]
Hi Mina,
We can have a call at 5pm if that's good for you.
Dave

**Comment by sohilpandya** [comment]
Yeah that works. we will invite you to a google hangout for 5.

**Comment by rickardinho** [comment]
Hi @sohilpandya I tried this out and I can edit the event, but there is no Save button to save the changes I've made to the event and return to the feed.  Therefore reopening this issue.
Dave

**Comment by sohilpandya** [comment]
Hi @rickardinho, I think you have reopened the wrong issue, This issue relates to editing a poll, which we discussed during the skype call.

At the moment, the button only appears if you have filled out all the fields (with the exception of notes), would you like us to change it so that the button appears at all times?

**Comment by rickardinho** [comment]
OK @sohilpandya, so I've created a poll which has What as "TBC" and When as "TBC", with Were having two options polling.  I think Edit should be available all the time, as I might want to change one (or both) of the TBCs to firm up the What or When, either with a poll or just enter a single option.

**Comment by sohilpandya** [comment]
@rickardinho OK.
