### ISSUE TITLE
Toggling buttons results in text selection

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#194]
As its a webapp, if I click a button twice (i.e. to toggle on and then off), the chrome browser thinks its a tap and hold, and tries to select the text, rather than click the button, this can be annoying.  Is there a way we can delay the time for a tap and hold to register?  Or else turn off the text selection.  see screenshot for example of this.
![shot_2016-05-21_11-42-34](https://cloud.githubusercontent.com/assets/17908724/15448654/e31d6c18-1f5f-11e6-80f3-ea6253fab3a7.png)

**Comment by sohilpandya** [comment]
Hi @rickardinho, are you pressing and holding or just touching the button. we have tried this on our phones and the copy functionality only appears when we press and hold the options.

**Comment by rickardinho** [comment]
Hi @sohilpandya, yes its when i tap and hold, but ive done it quite a few times accidentally, i wonder if its my phone settings where i have a shorter tap and hold time set?  leave it for now and i'll investigate my end to see if i can adjust them... i just wondered if there was an option to turn this off?

Dave

**Comment by minaorangina** [comment]
@rickardinho Had a little look into this: there are ways to try and prevent text from being highlighted, but apparently it would behave slightly differently from browser to browser / device to device.  So depends if you want to try it out or not

**Comment by rickardinho** [comment]
Hi @minaorangina,
I would leave it for now. Let's test the final prototype with a number of devices and we'll see how big an issue it is.
Dave
