### ISSUE TITLE
Feed showing incorrect picture against events created by me

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#195]
The feed is showing Damian's picture against events that Dave (You in the below screenshot) has created.
![shot_2016-05-21_11-39-16](https://cloud.githubusercontent.com/assets/17908724/15448678/44a7de14-1f60-11e6-8bcc-946881d6af9e.png)

**Comment by sohilpandya** [comment]
Hi @rickardinho, we have updated the structure of the database, which we think has caused this issue.

We will be moving to the new instance of the database soon, and we can see if this issue still exists there.

**Comment by sohilpandya** [comment]
@rickardinho this has been fixed and will be pushed to the live site soon.

please check and get back to us on this issue.

**Comment by rickardinho** [comment]
Looks to be fixed.  Will keep an eye out for any recurrence.
