### ISSUE TITLE
Setup Paid Database in heroku

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#197]
Hi @rickardinho & @Dameodeare 

hope you are doing well, we've just invited you to the app on heroku, once you've joined the app, we will transfer the ownership over to one of you so that we can get the paid database plans set up.

please let us know once you've joined, so that we can let you know the next steps for setting up the database plan.

**Comment by Dameodeare** [comment]
I've joined

**Comment by sohilpandya** [comment]
@Dameodeare great! we would like one of you to set up the following database plan for the app. who would be the best person to transfer the ownership of the app to, in order to set this up?

We would like you to set up the redis cloud database plan for the app as shown in the screenshots below. 
![screen shot 2016-05-23 at 11 47 18](https://cloud.githubusercontent.com/assets/2305591/15468473/556a8aee-20dc-11e6-8311-a1dd5fe1f554.png)
![screen shot 2016-05-23 at 11 47 26](https://cloud.githubusercontent.com/assets/2305591/15468475/594b7ce0-20dc-11e6-9c00-646b36f6d025.png)

**Comment by rickardinho** [comment]
Hi @Sohilpandya,

I tried this, but i got the error below... apparently we're no the app
owner.

Dave
[image: Inline images 1]

**Comment by sohilpandya** [comment]
@rickardinho you can try that now, we have transfered ownership over to you.

**Comment by rickardinho** [comment]
Hi @sohilpandya ,
All done now.
Dave

**Comment by minaorangina** [comment]
Thanks @rickardinho
