### ISSUE TITLE
Address Logic to display in WHERE

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#203]
Hi @minaorangina and @sohilpandya,

I have summarised my thoughts on how the address should be displayed below using basic logic -but not code :( 
I've also put the use cases of each beneath each one.
Address = what is returned from the Google places API (roughly).
Let me know if you want me to explain better.  The idea is to trim the text to be displayed in the voting button and in event details as some of the addresses we've been getting showing up have been really long with duplication of street addresses and other fields.

Dave's address Display Logic

IF Address =
Name, Street, Town, City, Country, Postcode
THEN display
Name, Town, Postcode
Eg. The O2, Greenwich, SE10 0DX
Use case: gig / concert / sports event

IF Address =
House No, Street, Town, City, Country, Postcode
THEN display
House No, Street, Town, Postcode
Eg. 10, Kingsland Road, London, E13 9PA
Use case: House party / BBQ

IF Address =
Town, City, Country, Postcode
AND Country = local country
THEN display
Town or City
Eg. St Albans or London
Use case: Bowling or Reunion

IF Address =
City, Country
AND Country NOT local country
THEN display
City, Country
Eg. Lisbon, Portugal
Use case: stag do/holiday

IF Address =
Country
THEN display
Country
Eg. Spain
Use case: holiday

**Comment by minaorangina** [comment]
@rickardinho Thanks.  Currently we are pulling the entire address string from the Google Places API, so the address data does not exist in each of its constituent parts.  We can edit our configuration of the API so we can get the separate address properties.  We'll have to come back to this

**Comment by minaorangina** [comment]
@sohilpandya The code for this part will need refactoring - it's quite sprawling and imperatively written at the moment.  Should really be its own function(s).

Also I've spotted the code isn't catching all address possibilities.  If you try Epping Forest, it disappears.  Glancing at the code, it's because only a few location `types` are being handled.  Epping Forest comes under `natural_feature` / `establishment`, neither of which the code recognises as a valid category.  

It would be a good idea to check the Google Places API to explicitly see what all their different location types are, and make sure you're handling all of them.

**Comment by sohilpandya** [comment]
@minaorangina, I have separated out the function into a different file, have a look in the branch. 

Here are a list of all the place types. There are a lot of them, and an else statement in the function above does not work as all of the responses are then being caught by the else statement. does that mean we have to list each of these in a separate if statement? or you think there's a neater way?


![screen shot 2016-06-16 at 20 15 28](https://cloud.githubusercontent.com/assets/2305591/16129995/2522823e-33ff-11e6-8f19-7f40de111fa2.png)

**Comment by rickardinho** [comment]
Hi @sohilpandya ,
I've noticed that the new address logic is always displaying Greater London instead of London. see screenshot below... it think before it was showing London for venues within London.  Can we change this back somehow?
![screenshot_20160628-151045](https://cloud.githubusercontent.com/assets/17908724/16432457/ff77c2e2-3d7c-11e6-868e-b2b165a12457.png)

**Comment by sohilpandya** [comment]
@rickardinho can you please check, it should be showing london for the above now instead of Greater London.

Thanks

**Comment by rickardinho** [comment]
Hi @sohilpandya , I'm still getting some inconsistent treatment of places... For example, Regents Park doesn't show the City, just the postcode, but Hyde Park and Southwark Park show London - see below.
![screenshot_20160629-205920](https://cloud.githubusercontent.com/assets/17908724/16466803/71316b08-3e3c-11e6-9b57-4c0bafcbbf2b.png)

**Comment by sohilpandya** [comment]
Hi @rickardinho, this is an interesting one. As you can see in the screenshot's below, Google categorises Hyde park as a type: Point of Interest and Regent's Park as a type: political. Which is very strange.

I have made a change and Regents Park will appear in the correct format with London as well as the postcode.

Changes will be pushed up in the morning and will update you once they are ready to test. 

![screen shot 2016-06-29 at 23 38 37](https://cloud.githubusercontent.com/assets/2305591/16471121/a4f88316-3e52-11e6-9095-23b6797ae407.png)
![screen shot 2016-06-29 at 23 37 32](https://cloud.githubusercontent.com/assets/2305591/16471122/a5122bae-3e52-11e6-9f91-6b5354d5e36f.png)

**Comment by rickardinho** [comment]
So where is the address, city, postcodes, etc in this string?  can we not just parse it based on town, city, country and postcode?

**Comment by minaorangina** [comment]
@rickardinho Sadly it's not quite that simple. This might be worth a phone call. Are you available for one at any point today?

**Comment by rickardinho** [comment]
Can do.  Is 3pm okay for a call?

**Comment by minaorangina** [comment]
@rickardinho Thanks, that works.

**Comment by rickardinho** [comment]
great, do you have a number for me to call you on?

**Comment by sohilpandya** [comment]
Yeah, I'll email you my number.
