### ISSUE TITLE
Make voting buttons similar sizing

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#204]
Hi @minaorangina ,
As discussed a few weeks ago, we think we should make all voting buttons in what where and when the same size as those in each section (i.e all what’s the same size, all where’s the same size, etc).   We think this is better from a design perspective and looks neater.  The issue will be the long text on locations.  I have an idea for this which I have raised as a separate issue #203.

Dave

**Comment by rickardinho** [comment]
Hi @minaorangina,
i thought this issue was fixed, but see the example below where the 3rd where option is a different size.
previously they were all the same size within each section.
![screenshot_20160628-150853](https://cloud.githubusercontent.com/assets/17908724/16429329/0aac2f4a-3d6e-11e6-832e-d3371d4ec437.png)

**Comment by minaorangina** [comment]
@rickardinho If the text for the option is really long, the voting button will always expand to accommodate it.  I'm going to make the text size shrink a bit if it's beyond a certain length.  It's not a perfect solution (e.g. it won't consider different screen sizes etc), but it could help

**Comment by minaorangina** [comment]
@rickardinho Here's a screenshot of what I've come up with:

![screen shot 2016-06-29 at 15 35 15](https://cloud.githubusercontent.com/assets/8915092/16456231/241ebd8e-3e0f-11e6-9931-b6a119d70d05.png)

You'll notice that all the buttons are slightly slimmer, but not exactly the same size.  A voting button with an extra line of text will always be larger than a voting button without one.  Really not much of a way around this.

Tell me if you prefer my screenshot or yours and I'll implement.

**Comment by rickardinho** [comment]
@Dameodeare what are your thoughts?

**Comment by rickardinho** [comment]
hi @minaorangina , we've agreed to leave it as it is.  Close the issue if you're happy.
Thanks,
Dave
