### ISSUE TITLE
create edit note input field

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#221]

**Comment by sohilpandya** [comment]
- [ ] create note in the event description section - add it below the name and description, make it non-mandatory
- [ ]  add it to the state
- [ ] push this to the event object in the backend 

- [ ]  add this in all the view event sections so the note can be read if present

- [ ]  add the field for this to edit event section

**Comment by sohilpandya** [comment]
@minaorangina can we close this one?
