### ISSUE TITLE
Upload photo to S3

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#224]
With a test please 😄 

Relates to #205

**Comment by sohilpandya** [comment]
https://www.npmjs.com/package/imagemin

**Comment by sohilpandya** [comment]
https://www.youtube.com/watch?v=VC0k-noNwOU

**Comment by sohilpandya** [comment]
https://github.com/aheckmann/gm
https://github.com/adamhenson/s3-image-uploader
https://github.com/imagemin/imagemin
http://aws.amazon.com/developers/getting-started/nodejs/
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#uri=https://www.npmjs.com/package/aws-sdk

**Comment by sohilpandya** [comment]
### Setup

##### On Amazon
- Create a Unique Bucket
- in IAM Roles, add the new Bucket and Provide Permission of `AmazonS3FullAccess`

##### On Local
- Add `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` to your env or config. 
- use the REST API Example as a starter guide for making requests to AWS S3! http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-examples.html

**Comment by sohilpandya** [comment]
Add Buildpack to heroku for imagemagick
https://devcenter.heroku.com/articles/third-party-buildpacks

**Comment by sohilpandya** [comment]
http://stackoverflow.com/questions/28423201/how-can-i-use-the-latest-version-of-imagemagick-on-heroku
