### ISSUE TITLE
Transfer ownership of heroku

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#227]
Hi @rickardinho could you please transfer back the ownership of the app on heroku to Mina.

We would like to transfer the data from the old db to the new db and only the app admin can do this. 

Thanks

**Comment by rickardinho** [comment]
Hi @sohilpandya and @minaorangina 
I have transferred ownership back to Mina.
Dave

**Comment by sohilpandya** [comment]
Thanks
