### ISSUE TITLE
Event screen not loading from Feed

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#229]
Hi @minaorangina and @sohilpandya,
I opened the app this morning and created a couple of events. The second of which I clicked on Cancel.  Now I don't seem to be able open any event from the feed. When. I click on an event in the feed I get the refreshing progress blobs, but the page never seems to load. I am in France at the moments, I'm not sure if that would make a difference. Is this due to the new database?

**Comment by minaorangina** [comment]
@rickardinho I transferred the database a couple of hours ago, possibly you were creating your events at the same time, and data has ended up split between the two.  I've just deleted your most recent events from the new database - have another go and see if it's ok.

**Comment by rickardinho** [comment]
@minaorangina I'm still getting the same problem as of 2 minutes ago.
Dave

**Comment by minaorangina** [comment]
@rickardinho Spotted there was a bug, should be fixed now if you try again?

**Comment by rickardinho** [comment]
@minaorangina Looks to be working correctly now.  I'll close this issue.
