### ISSUE TITLE
Facebook Authentication

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#25]
### Resources
[Redux-Saga article](https://medium.com/@MattiaManzati/tips-to-handle-authentication-in-redux-2-introducing-redux-saga-130d6872fbe7#.k6y4733bt)

**Comment by sohilpandya** [comment]
https://github.com/joshgeller/react-redux-jwt-auth-example

**Comment by minaorangina** [comment]
[Authentication with React Router](http://www.tech-dojo.org/#!/articles/5697fd5ddb99acd646dea1aa)

**Comment by sohilpandya** [comment]
https://auth0.com/blog/2016/01/04/secure-your-react-and-redux-app-with-jwt-authentication/
