### ISSUE TITLE
Unable to confirm event if no date specifed and isPoll is false in create event flow

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#262]
So when the user gets to the final detailed view for create event, if the date is left blank and isPoll is false (i.e. its a confirmed event) then the user should not be able to create the event. 

They have to go back and enter the date. (link the what title to the what page)

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare  Just to continue from the discussion in #205 - making a confirmed event is impossible if you haven't specified a date.

In the case where no end time has been specified, we're going to make events default to move across to the album on 6am the next day.  If no start time is specified, the default start time will be midnight.

Sound ok?

**Comment by Dameodeare** [comment]
sounds fine by me.

**Comment by rickardinho** [comment]
Yes, that's correct.
