### ISSUE TITLE
On When/Event screen, dates selected in poll should be sorted chronologically

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#266]
On When/Event screen, dates selected in poll should be sorted chronologically once they are entered.
This should be on the screens attached.

**Comment by rickardinho** [comment]
![shot_2016-06-07_09-22-49](https://cloud.githubusercontent.com/assets/17908724/15852480/075ee570-2c99-11e6-83c1-50820709801e.png)
![shot_2016-06-07_09-23-39](https://cloud.githubusercontent.com/assets/17908724/15852492/12723994-2c99-11e6-85da-3c7e2891bfe9.png)

**Comment by rickardinho** [comment]
In the screenshots above, in the 2nd the date is chronological, whereas in the first they are out of order.  Both the screens should apply some sorting to put these in date order as this makes more sense for the user.

**Comment by sohilpandya** [comment]
@rickardinho can you please test this out, it should be fixed now. 

Please close if fixed.

Thanks

**Comment by rickardinho** [comment]
Yes, this is fixed.
