### ISSUE TITLE
Add Event title and friend details to Feed

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#268]
Adding the Event Title to the feed and details of how many friends have been invited as per our original screen designs.

**Comment by sohilpandya** [comment]
@rickardinho can you please test this out, it should be OK now. 

Please close if fixed.

Thanks

**Comment by rickardinho** [comment]
@sohilpandya Some events say "undefined friends".  See screenshot.

![shot_2016-06-08_21-57-54](https://cloud.githubusercontent.com/assets/17908724/15911912/bdd63eee-2dc9-11e6-9f2c-773ddf1c2709.png)

**Comment by sohilpandya** [comment]
@rickardinho thats due to older notifcation objects not having the number of invitees inside of it.

We will be flushing the db later today, so that we only have events with all the items in notification feed.
