### ISSUE TITLE
Text description not wrapping properly on iphone

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#269]
Iphone only - description text in event details does not wrap properly on iphone 5s, and if swipe right the screen scrolls (see screenshots) - whereas on Android it wraps the text ok.
![description after scrolling right](https://cloud.githubusercontent.com/assets/17908724/15848963/c321686c-2c87-11e6-8af4-238637bc9e35.PNG)
![description not wrapping](https://cloud.githubusercontent.com/assets/17908724/15848964/c327f826-2c87-11e6-8393-dbf15bbb3af4.PNG)

**Comment by sohilpandya** [comment]
@rickardinho can you please test this out, it should be fixed now. 

Please close if fixed.

Thanks

**Comment by rickardinho** [comment]
Fixed.
