### ISSUE TITLE
PNG icon

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#291]
Hi @rickardinho @Dameodeare 

Can we please get the PNG version/SVG version of the logo please.

Thanks

**Comment by rickardinho** [comment]
![iconspark 2](https://cloud.githubusercontent.com/assets/17908724/15935060/e92f3e30-2e5d-11e6-8736-24e6882ebeef.png)
![logospark 2](https://cloud.githubusercontent.com/assets/17908724/15935061/e9521806-2e5d-11e6-8078-1c520b50b956.png)

**Comment by rickardinho** [comment]
Hi @sohilpandya not sure if you received these icons okay?  If not i can email them.

Dave

**Comment by sohilpandya** [comment]
Hi @rickardinho have you got the high res file which you can email us? 

Also do you have a copy of the image without the white ring surrounding the border, mobile icons with this version does not look good.

**Comment by rickardinho** [comment]
Do you mean a version without the border? I think the iPhone icons are more
rounded than android, so probably best to not have the border.
