### ISSUE TITLE
Logic for TopBar

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#302]

**Comment by sohilpandya** [comment]
@minaorangina I have fixed this locally, but unable to push online as I created a branch off your resocket branch, and the following test is failing for me. 
` Socket port matches the server port`
What changes do I need to make to make the test pass? 

Thanks

**Comment by minaorangina** [comment]
@sohilpandya you need to set an environment variable in circleci. PORT=9001

**Comment by sohilpandya** [comment]
Thanks. had to set that in test-env. 👍

**Comment by sohilpandya** [comment]
@minaorangina might be worth merging your resocket branch before merging my topbar branch.
