### ISSUE TITLE
Adding Options

### ISSUE THREAD

**Issue by Dameodeare** [DRDD2016/app#307]
When you are adding an option, say in "What", if you have typed in an option  and then pressed in the "add option" box, the cursor should move there and the ability to type the next option should happen, without haveing to repeat the steps.  this will be a better user experience.

we can call to go through this tomorrow if needed.

**Comment by minaorangina** [comment]
Hi @Dameodeare, I see what you're describing, so no need for a call.  At the moment my top priority is to get the real-time feature up and running by Friday at the latest (likely to take a few days).  Happy to look at this after that's complete, if time allows.

**Comment by Dameodeare** [comment]
thanks Mina
