### ISSUE TITLE
Display attendance status in calendar

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#323]
- [x] For each event, search for User RSVP.  Return 'not responded' if none found.
- [x] Combine RSVP status with event info
- [x] Update UI to display RSVP status
- [x] Display attending / not attending / maybe / not responded icons

**Comment by minaorangina** [comment]
@Dameodeare @rickardinho What did you want displayed for not attending?

**Comment by minaorangina** [comment]
@Dameodeare @rickardinho I haven't managed to find a 'maybe' icon like the image you sent in the email.  Perhaps [this one here](http://fontawesome.io/icon/question-circle/) would work as an alternative?

Otherwise you can see all the icons I have available to me [here](http://fontawesome.io/icons/).  If you find one you like, let me know its name and I'll use that.

**Comment by rickardinho** [comment]
Hi Mina,
Let's go with green tick (going), amber question mark (maybe), red cross
(not going), grey exclamation mark (not responded).

Is that okay?
Dave

**Comment by minaorangina** [comment]
@rickardinho Yep that's fine, will make those changes.
