### ISSUE TITLE
Enlarge friend labels

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#324]
- [x] Make text / image for invitee larger
- [x] Ensure correct alignment

**Comment by rickardinho** [comment]
They are still small on the Confirm screen... just before sending a poll.  Can we make this screen like the others.
![screenshot_20160628-000048](https://cloud.githubusercontent.com/assets/17908724/16398882/e2c98ef8-3cc5-11e6-92fb-d4d320b47df7.png)

**Comment by rickardinho** [comment]
Also they are still small when I click back and then try to remove a friend.
https://lh3.googleusercontent.com/bDNI0ZuPizUsdPNOIlxnqe08SV4zc8dTORvcIKdqv7IKtiDuFN0xrege6SaNq1Tyeft1Y9odVF__z3v9BuTeD9tT7xG5u5lqcq3iiJxlUzPTKPtsIl3JTO14CqyVA1ShXs-MNg0wG9Z2S1ii6Wfo7PqdWQ1oHCCcDdJ0CSWyVoFWpvnFR7iaL8__Mc-5htSOdl25jYhk2ZZCyc4lu1hrecD6Y5rrL5gsLG7iPZ6B4B8SrL824ucr03Ng0pgKuWfLZRXFmaVyWqzaplWqCO4fngKgKm92uw-gtykWfpK3jH55FGfPIJP1qAah_dpjynO12QxCz4-H13eqjX9QQQnkpOxLCFTP0gEQdI2xmClsi-k4xyqeBWqWOI7KTcWIlGUytnx8xbcQInO-kOZ89cEGB4oYv4DTMzZcbmREEOGV83jvGjTrFK8Xz109k10dXkOytnB-ye1EUVeo40weyD3faMLd8zoXEJHfKLJP85iMGxod39Qvl26PY-RrgX60iG1HImKGnIKoX-Q5K2RbasHh9Mv17SyawfNF7nKwIYrKz_Sde_pzJRiEE0C45q884_zGK2xCVO6HgRAtUgpinEyEN9VRC_rP7W1x=w355-h631-no

**Comment by minaorangina** [comment]
@rickardinho i've enlarged them now, please check when you can.
