### ISSUE TITLE
Replace upload photo button

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#325]
- [ ] replace button with a dialogue box
- [ ] box appears after file is selected (possibly use listener to detect if file is defined within store)
- [ ] box disappears on click of upload
- [ ] determine how to prevent box reappearing at the wrong time

**Comment by sohilpandya** [comment]
@minaorangina for now I've moved it above the upload button so that it appears first when an image is selected.

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare Sadly we've not had any time to do to this - we had to spend a lot of time on #323
