### ISSUE TITLE
General formatting

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#326]
- [x] Event details page: fix typo (an --> **and**)
- [x] Host poll: numbers aligned and smaller.  Colour to match category
- [x] App splash page: white background with full Spark logo.  Text removed.
- [x] Both poll pages: options === *eight columns*, category label === *three columns*, count === *one columns* (give or take as appropriate)
- [x] Feed: Match wireframes
- [x] Profile: logout button === *six columns* with offset to centre
- [x] Home screen icon - replace with borderless version
- [x] Confirmed event: remove filename
- [x] Both poll pages: reduce margin on h tags
- [x] Host poll: fix dodgy alignment with *when* options

**Comment by sohilpandya** [comment]
@minaorangina Home screen icon for android has been changed, but would like you to try it out once we push live again.

**Comment by rickardinho** [comment]
Hi @minaorangina,
can the splash screen have the full spark logo with the text (identical to the login page) as we discussed.
Then remove the Spark text at the bottom as we don't need Spark twice.
Thanks

**Comment by sohilpandya** [comment]
Hi @rickardinho, unfortunately that is not possible to do, as the splash page is built by google using a manifest file that we are providing, it takes the Title, Home-Screen Icon and creates it using the provided information.

**Comment by rickardinho** [comment]
Hi @sohilpandya,
the spark logo which appears on the home screen no longer has the rounded corners, (its a perfect square).  Can we have these back in as i think it looked neater.  Only action was to remove the multicoloured border, not to change the overall shape.

**Comment by sohilpandya** [comment]
Hi @rickardinho, the borderless logo that you had sent me to replace the old one came in that shape, hence it has now changed.

could you please forward me the logo with the rounded corners so that I can replace the square one. 

Thanks

**Comment by rickardinho** [comment]
Feed isn't quite looking right... compare the app currently, to the wireframe.  Event title needs to be bolder and the "VOTE" text next to the icons on the right is not aligned.  Can we make the font size and icons for location and date are a bit bigger too, with similar font size and font type to the wireframe. Also, can we put a grey border round the whole item in the feed so that they look like clickable 'cards'?  
![screenshot_20160629-212347](https://cloud.githubusercontent.com/assets/17908724/16467728/85c925ac-3e40-11e6-9f48-8c11065aa308.png)
![screenshot 2016-06-29 at 21 24 18](https://cloud.githubusercontent.com/assets/17908724/16467763/9c0e3604-3e40-11e6-9db6-52dd63e21a51.png)

**Comment by sohilpandya** [comment]
@rickardinho can you please have a look at the screenshot below, we've implemented what you've asked for above, we can discuss this on the phone.  

![screen shot 2016-06-30 at 14 11 54](https://cloud.githubusercontent.com/assets/2305591/16489264/a5de5c4a-3ecc-11e6-9efc-b5d02eb9e41d.png)

**Comment by sohilpandya** [comment]
@rickardinho Please have a look at this comment above, and once you are happy with it, we can push this alongside all the other fixes/css changes to the live app for you to test.

**Comment by rickardinho** [comment]
This looks great.... but I think the event title (eg. Arsenal v Tottenham) should be the same font, weight, size and colour as the event title on the calendar screen.
I like the cards look for the border. Can we add this to the albums and calendar screens too.  Then make the other fonts, weight and colour consistent on albums and calendar to this feed, if they are not already.
Finally, can we remove the "TH", "RD" from the dates in the feed, so it just reads "30 JUN".
Thanks
Dave
