### ISSUE TITLE
Filter panel should not disappear

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/app#327]
- [x] Look at master events array, instead of filtered

**Comment by rickardinho** [comment]
hi mina, we'd need to refresh the database to test this wouldn't we?

**Comment by minaorangina** [comment]
@rickardinho that's true.  I'll wipe it now.

**Comment by rickardinho** [comment]
@minaorangina @sohilpandya , This looked okay for me, but Damian thinks its still not working.  Can we flush the db again so we can retest?

**Comment by minaorangina** [comment]
@Dameodeare @rickardinho I've just emptied out the database, so you're free to test this out now

**Comment by rickardinho** [comment]
@minaorangina @sohilpandya We just tested this its not fixed I'm afraid.   I sent Damian an invite.  I then clicked on Received and i get the screen below, with no buttons so i can't get back to All or Hosting to see the invite i created.
![screenshot_20160630-170624](https://cloud.githubusercontent.com/assets/17908724/16495439/5ebe50c2-3ee5-11e6-8bc6-a3f7e4565a2c.png)

**Comment by rickardinho** [comment]
Calendar works okay, its just the Feed.

**Comment by minaorangina** [comment]
@rickardinho thanks, I'm making some changes now to fix this

**Comment by rickardinho** [comment]
@minaorangina this looks like its fixed now thanks.

**Comment by minaorangina** [comment]
@rickardinho Oh, I emptied the database a moment ago and was just about to inform you, but you're a step ahead :)
