### ISSUE TITLE
Feed doesn't load

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#347]
Feed doesn't load but just shows progress bar indefinitely, other screens are fast to load, its only the feed that seems to freeze.

**Comment by rickardinho** [comment]
I'm also having trouble loading events when i click on them.  Not wifi/connection related as other apps and internet sites working fine.

**Comment by minaorangina** [comment]
@rickardinho Not really sure about this one.  If it happens again, note down the time in this issue and I'll have a look

**Comment by minaorangina** [comment]
@rickardinho As mentioned in #355, we spotted a bug and have fixed it.  Please test by creating polls with at least one confirmed category (i.e. a category with only one option)
