### ISSUE TITLE
Overlapping buttons

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#352]
When entering a poll and then going Back, and then finalising the poll, when I get to the Confirm screen to confirm an event i got the buttons overlapping each other as in the screenshot below.  This happened about 10 mins ago before you flushed the database so not sure if you can track it.
![screenshot_20160628-130152](https://cloud.githubusercontent.com/assets/17908724/16414967/bdc5721c-3d32-11e6-92be-133259cac1d8.png)

**Comment by rickardinho** [comment]
Another example of overlapping buttons before sending Poll
![screenshot_20160628-132618](https://cloud.githubusercontent.com/assets/17908724/16429181/5bf1d8ec-3d6d-11e6-9298-7f29b198b03d.png)

**Comment by sohilpandya** [comment]
@rickardinho can you please check this out, should be ok now.

**Comment by rickardinho** [comment]
Looks okay now.  Thanks
