### ISSUE TITLE
Some items in feed won;'t open

### ISSUE THREAD

**Issue by Dameodeare** [DRDD2016/app#355]

**Comment by Dameodeare** [comment]
Hi,

Some items in the feeed, created today, won't open.  I just get the thinking dots for minutes, andhave to exit the whole app to get out..

Some other invites from the same people work.  And this has happened with invites from 2 different people.

Let me know if you need more - I'm sure you do.

Damian

**Comment by rickardinho** [comment]
I'm getting the same issue.  The whole app goes unresponsive when clicking some items in the feed.  It appears to not be all items, but the same events are consistently causing the issue.

**Comment by sohilpandya** [comment]
Hi @Dameodeare @rickardinho, could you please talk us through the whole user flow that you are going through to get this issue.

Is the Event a Poll or a Confirmed Event. 

Just trying to get more information with regards to these unresponsive events so that we can try to debug it as we've not had this unresponsive behaviour. 

Thanks

**Comment by rickardinho** [comment]
Basically, when I go into the Feed, if Damian has invited me to a poll, when I click on it, then i get the 3 progress blobs and nothing ever happens.
I think he's getting the same thing if i send a poll to him.

**Comment by Dameodeare** [comment]
the 2 i have noticed so far are polls. But it doesn't happen on all polls.

I've left it running for minutes and it just stays thinking,

**Comment by sohilpandya** [comment]
Can you please test, we found a bug that was causing certain polls to hang. 

This should no longer be the case.

Regards

**Comment by Dameodeare** [comment]
do we know what was causing it - i.e. what certain factors in creating a
poll have changed, that will make it easier/quicker to test.

Thanks

**Comment by sohilpandya** [comment]
@Dameodeare you can create some polls where one of the (what, where or when) is confirmed and the others have more than one option.
