### ISSUE TITLE
Problems editing the "What" when creating event

### ISSUE THREAD

**Issue by Dameodeare** [DRDD2016/app#356]
if you fill more than one field in the "what" and then try going back into an already entered field to try and edit it, as soon as you press a letter the cursor jumps back down to option 3.

i can send a video if it's easier..  let me know if you need more

**Comment by sohilpandya** [comment]
Hi @Dameodeare this is linked to #307 could you please have a read through that and get back to us whether you would like to keep the feature or not. 

Thanks

**Comment by Dameodeare** [comment]
But if i want to edit a previous entry, i don't understand why it moves down to the lowest box again after i press a single key.

Are you saying that this issue is linked - i.e we can't have the functionality of issue #307 without incurring the problem above?  If so, can you explain why?

Thanks

**Comment by minaorangina** [comment]
@Dameodeare Yes that's correct - though in the last hour we've found a workaround, so this should actually be fine in the end.

**Comment by Dameodeare** [comment]
Great - thanks Chap(esse)s

**Comment by sohilpandya** [comment]
Can you please test and close.

Thanks
