### ISSUE TITLE
Can't select poll option

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#364]
When replying to a poll, if i try to click a poll option to select it, it take me back to the Feed rather than selecting the item. This only started happening this evening.
In the screenshot below, if i click any location or time, it goes straight to the feed.
![screenshot_20160629-215755](https://cloud.githubusercontent.com/assets/17908724/16468666/da8be2a6-3e44-11e6-82ef-db636fd4ce20.png)

**Comment by sohilpandya** [comment]
@rickardinho, I've just fixed this on the local, will push this up onto the live site first thing in the morning tomorrow.
