### ISSUE TITLE
Issue Changing name on "Profile" Screen

### ISSUE THREAD

**Issue by Dameodeare** [DRDD2016/app#367]
When I go to the "Profile" screen, my name updates above the profile photo as I change it in the text box.  Pressing the "Change Name" Button has no effect and seemingly does nothing.

Can we change it to a more traditional idea - as in type the name into the text box, then when you are happy press the "change name" box, and the app goes back to the feed screen with the name having changed.

Thanks.

**Comment by sohilpandya** [comment]
When you select Change user name it will now redirect you to the feed.
