### ISSUE TITLE
More formatting changes

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#377]
1. Can the heading font on each page be +2pts bigger and bold to stand out a bit more from the background image.
2. Can the title of the event on each page (i.e. poll and confirmed event screens) be bold and same font size as on the What, Where, When screens. Also can the vertical alignment be centred like on What screen.(see screenshots below)
![screenshot_20160630-222601](https://cloud.githubusercontent.com/assets/17908724/16506538/00eb543c-3f1b-11e6-8718-8e71a80edf37.png)
![screenshot_20160630-233408](https://cloud.githubusercontent.com/assets/17908724/16506592/6cc3f72c-3f1b-11e6-8600-82d020ffe886.png)

**Comment by rickardinho** [comment]
can we also change the text "event photo stream" to read "Photos" and centre this.

**Comment by sohilpandya** [comment]
@rickardinho can you please test.

Thanks
