### ISSUE TITLE
choose file to upload button not displaying correctly on iphone 5s

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#378]
see screenshot... text appears fainter than android and is barely readable.
![image4](https://cloud.githubusercontent.com/assets/17908724/16506744/587a43a6-3f1c-11e6-868d-ceef35fac20c.PNG)

**Comment by minaorangina** [comment]
@rickardinho I can make the font bolder, but it will be bolder in both Safari and Chrome - I can't make the text bold in one browser and not in the other.

I'll try making it only slightly bolder and I'll add a screenshot here

**Comment by sohilpandya** [comment]
@rickardinho We've made the change, this is how it looks on iPhone's is this font weight ok?
![screen shot 2016-07-01 at 12 00 28](https://cloud.githubusercontent.com/assets/2305591/16519812/8e34ba3c-3f83-11e6-94e1-c80e6192d9d3.png)

**Comment by minaorangina** [comment]
And here's how it looks on android.  If you're happy with this we'll push the changes to the live app.
![img-20160701-wa0000 jpg](https://cloud.githubusercontent.com/assets/8915092/16519888/1d4ac446-3f84-11e6-85f8-5453c3846f93.jpeg)

**Comment by sohilpandya** [comment]
@rickardinho can you please test.

Thanks
