### ISSUE TITLE
black screen when choosing camera to choose photo on iphone 5s

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#381]
when selecting choose a file to upload ---> camera on iphone 5s, the camera appears but with a black screen
![image3](https://cloud.githubusercontent.com/assets/17908724/16506990/3dfd87ca-3f1e-11e6-8c1a-cb3a36488154.PNG)
... see screenshot.

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare Strange, but unfortunately we have no control over this whatsoever.  This may well be a bug with the phone/operating system itself.

**Comment by sohilpandya** [comment]
Hi @rickardinho @Dameodeare

We've tried this on someone's 5s and seems to be ok. You might want to reset the phone or settings for it.

**Comment by rickardinho** [comment]
Okay, we'll investigate. Leave it for now.

**Comment by rickardinho** [comment]
Fixed this... we will add to our technical support documents and FAQs,
To fix... Go to Iphone Settings... Privacy... Camera... ensure Safari is enabled.
