### ISSUE TITLE
some screens showing Time TBC, some just show time icon

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#383]
see screenshots.  shouldn't we either hide the time icon or show TBC for the one which has a date but no time
![screenshot_20160630-233408](https://cloud.githubusercontent.com/assets/17908724/16507133/5e5b39c6-3f1f-11e6-9b87-280af6d885c5.png)
![screenshot_20160630-222711](https://cloud.githubusercontent.com/assets/17908724/16507134/5e5e65ce-3f1f-11e6-906d-4047820d950e.png)

**Comment by sohilpandya** [comment]
@rickardinho can you please test.

Thanks
