### ISSUE TITLE
Link Metatags for index.html

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#5]
- Make it more App like

**Comment by minaorangina** [comment]
[Example repo here](https://github.com/foundersandcoders/mind-yourself).  Find a more up to date way if possible

**Comment by sohilpandya** [comment]
http://blog.teamtreehouse.com/optimizing-mobile-web-apps-ios

http://taylor.fausak.me/2015/01/27/ios-8-web-apps/

**Comment by sohilpandya** [comment]
Potentially another tutorial to create json file if needed in the future. https://developer.chrome.com/webstore/get_started_simple
